### ISSUE TITLE
"Invalid file type" when uploading zip file to bundler web app

### ISSUE THREAD

**Issue by shaunabanana** [lovebrew/bundler-frontend#13]
First of all, thank you for the awesome work with all of the recent updates!

An issue I noticed with the bundler: when uploading a zipped project to the bundler web app, the web app responds with "Invalid file type" even though I seemed to have followed the instructions on the Wiki. Am I missing something?

### Steps to reproduce:
- Create a bare minimum project by creating the folder structure as shown [here](https://lovebrew.org/#/bundler/index?id=getting-started) and downloading the template TOML. (`main.lua` content copied from the "Hello, World" page.)
- Zip the contents using the system default archiver. I have tried both zipping the `SuperProject` and the contents of it, as the documentation was a bit unclear, and neither worked.
- Upload to the web app to get the response "Invalid file type".

### Environment:
- macOS Sonoma 14.0

**Comment by shaunabanana** [comment]
Oops! Forgot to include info on the browser. I've tried both Arc and Safari.
- Arc Version 1.15.1 (43023), Chromium Engine Version 119.0.6045.105
- Safari Version 17.0 (19616.1.27.211.1)

**Comment by TurtleP** [comment]
I'm not entirely seeing where this could crop up. The only place this error shows is when you supply an invalid file type, i.e. not an image, font, or acceptable zip. 

The former include: `image/png`, `image/jpg`, `font/ttf`, and `font/otf` but are purely for 3DS conversions. 

The zip is expecting `application/x-zip-compressed`. It could be that the zip (at least that's what it sounds like you're uploading) that has the content, etc isn't matching the expected mimetype. For what it's worth, I have only tested zips created on Windows, not using something like 7zip or other applications. It's entirely possible that the mimetype that's being uploaded *is* a zip, but not one of which we expect. If you could check that and upload your zip that you wanted, it would help diagnose the issue on our end.

**Comment by TurtleP** [comment]
It should also be noted that currently the fused game functionality isn't working, so bundling with the exe isn't working proper for the moment. I do have a commit/branch of LÖVE Potion that fixes this, but I need to be sure I'm fixing a lot of the little issues that also came up post-release.

If you need to convert 3DS assets, you can set `packaged` in the `build` section to `false`.

**Comment by TurtleP** [comment]
Okay, seems that the issue should be fixed. As expected, a minor mimetype issue was the cause. We didn't use the mimetype library for zips, only images and fonts. The site has been redeployed with the fix. Let me know if it works for you now (I've tested with a zip from macOS so it should be fine).

**Comment by shaunabanana** [comment]
Yes, the issue is resolved! Thank you very much!
