### ISSUE TITLE
Uploading multiple files on the bundler app uploads it multiple times creating useless copies

### ISSUE THREAD

**Issue by ZakiTale** [lovebrew/bundler-frontend#15]
uploading 4 images for example will make it send you 4 folders with each containing the 4 images, hence cloning it 4 times (well technically cloning it 3 times but you get the gist).

**Comment by TurtleP** [comment]
Could you try with the new beta website to see whether this is fixed? I'm not 100% sure I understand what you mean by it "cloning" it. If you have four separate images it's going to convert all four. It definitely wasn't the best way to do it on the stable version with the folders separating them, though. The beta site ends up using a single folder with all textures converted in it.

https://beta-bundle.lovebrew.org

**Comment by Nawias** [comment]
Fixed on the beta branch, but let's close this issue when it's merged to main.
