### ISSUE TITLE
Client-Side Optimizations

### ISSUE THREAD

**Issue by TurtleP** [lovebrew/bundler-frontend#4]
This has come up a lot of times with DeltaV. The suggestion is to optimize what we upload and download because otherwise it wastes a ton of bandwidth. This may involve parsing the TOML file, but whatever. The idea is the following:

1. Read the TOML file as a JSON object, find the console build information
2. Create up to three temporary zip files in memory, one per console. 
3. Should one of these builds be for Nintendo 3DS, iterate the source directory
    - For each file in here, check if we want to convert it: `.ttf`, `.otf`, `.png`, `.jpg`, `.jpeg`
    - Convertible files should be sent to the server _immediately_ for processing.
        - A converted file should be returned immediately and written to the proper in-memory zip file.
4. If the user requests building for Nintendo Switch or Nintendo Wii U:
    - Nothing requires converting, but wait for the server to respond with the resulting binary
5. When the server responds with their new binaries with metadata, append the game zips to the end of the data

> [!NOTE]
A server-side update will be required. The version number will increment, and documentation on the Wiki should reflect the new changes. See [Server-Side Optimizations](https://github.com/lovebrew/lovebrew-webserver/issues/7)

**Comment by Nawias** [comment]
I propose we split this into subtasks:
 - Create converter classes for fonts and images
 - Change how `bundler.ts` works to:
   1.  Request the binary with metadata from `/convert` (preferably cached)
   2.  Packs code and assets into the binary (JSZip should do the trick)

**Comment by Plep-m** [comment]
I can look at the 1st step as soon as i get home tonight

**Comment by Nawias** [comment]
Then for the converter classes I suggest:
- In `src/services` there should be a new `converters` directory
- We should have a `IMediaConverter` interface or `MediaConverter` partial class as base to `ImageMediaConverter` and `FontMediaConverter`
  - The base class should declare a `convert` method that takes a file and returns a `Promise` of the converted file 
- The converter classes should handle their respective API endpoints: `/convert/t3x` and `convert/bcfnt` 

Just to keep things structurally sound

**Comment by Plep-m** [comment]
Sounds great

**Comment by TurtleP** [comment]
> I propose we split this into subtasks:
> 
> * Create converter classes for fonts and images
> * Change how `bundler.ts` works to:
>   
>   1. Request the binary with metadata from `/convert` (preferably cached)
>   2. Packs code and assets into the binary (JSZip should do the trick)

The code and assets would already be in the in-memory zip, so you should be able to just take that and append it to the binary easily.

**Comment by Nawias** [comment]
Yes, but we need to convert some assets for 3DS and add them to the zip first

**Comment by TurtleP** [comment]
[Server Details](https://github.com/lovebrew/lovebrew-webserver/issues/7#issuecomment-1773013642). Changes are not pushed yet, trying to fix tests right now.

**Comment by TurtleP** [comment]
Changes to the server have been pushed to the branch, all tests passing now.

**Comment by Nawias** [comment]
A couple of notes:
 - Error handling in `App.tsx` should be reworked to and not rely on `BundlerResponse` interface anymore; we should just display messages from thrown `Error`s or promise `reject`ions as they come
 - `bundler.ts` should be generally nuked out of existence and written from scratch to account for the new flow
